logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.21.129
    port: 5672
    virtual-host: /
    username: root
    password: root
    listener:
      simple:
        prefetch: 1